env:
 - ZMQ="git://github.com/zeromq/zeromq3-x.git -b v3.2.3"
before_install:
 - sudo ln -s $TRAVIS_BUILD_DIR/test /test
 - sudo ln -s $TRAVIS_BUILD_DIR/ce-delta-hub /ce-delta-hub
 - sudo ln -s $TRAVIS_BUILD_DIR/ce-engine /ce-engine
 - sudo ln -s $TRAVIS_BUILD_DIR/ce-front-end /ce-front-end
 - sudo ln -s $TRAVIS_BUILD_DIR/ce-operation-hub /ce-operation-hub
 - sudo apt-get update
 - sudo apt-get install haproxy
 - sudo cp -f test-runners/standalone/haproxy/haproxy.cfg /etc/haproxy/
 - sudo cp -f test-runners/standalone/haproxy/haproxy /etc/default/
 - sudo apt-get install uuid-dev
 - git clone --depth 1 $ZMQ zmqlib
 - cd zmqlib
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
 - sudo /sbin/ldconfig
 - cd ..
 - git submodule update --init --recursive
 - git submodule foreach npm install
 - git submodule foreach npm test
 - cd test-runners/standalone
 - npm install
script:
 - npm start
 - sudo /etc/init.d/haproxy start
 - cat out.log
 - cat err.log
 - npm test
language: node_js
node_js:
 - "0.10"
