language: ruby
rvm:
  - "1.9.3"
before_install:
  - git submodule update --init --recursive
install:
  - VBoxManage -v
  - wget http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/vagrant_1.2.2_i686.deb
  - sudo dpkg -i vagrant_1.2.2_i686.deb
script:
  - /opt/vagrant/bin/vagrant up
