site :opscode

cookbook "zeromq", git: "https://github.com/pghalliday/cookbook-zeromq.git", branch: "0.0.0"
cookbook "haproxy", git: "https://github.com/pghalliday/haproxy.git", branch: "master"

cookbook "test-runner", path: "cookbooks/test-runner"
cookbook "ce-front-end", path: "../../ce-front-end/cookbooks/ce-front-end"
cookbook "ce-operation-hub", path: "../../ce-operation-hub/cookbooks/ce-operation-hub"
cookbook "ce-delta-hub", path: "../../ce-delta-hub/cookbooks/ce-delta-hub"
cookbook "ce-engine", path: "../../ce-engine/cookbooks/ce-engine"
