# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # enable hostmanager to add all machines to each other's /etc/hosts
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # install chef solo on all machines
  config.omnibus.chef_version = "11.4.4"

  # enable berkshelf
  config.berkshelf.enabled = true

  config.vm.define "ce-operation-hub" do |node|
    node.vm.hostname = "ce-operation-hub"
    node.vm.network :private_network, ip: "33.33.33.54"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../ce-operation-hub", "/ce-operation-hub"

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "ce_operation_hub" => {
          "destination" => "/ce-operation-hub",
          "user" => "vagrant"
        }
      }
      chef.run_list = [
        "recipe[ce-operation-hub]"
      ]
    end
  end

  config.vm.define "ce-delta-hub" do |node|
    node.vm.hostname = "ce-delta-hub"
    node.vm.network :private_network, ip: "33.33.33.55"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../ce-delta-hub", "/ce-delta-hub"

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "ce_delta_hub" => {
          "destination" => "/ce-delta-hub",
          "user" => "vagrant"
        }
      }
      chef.run_list = [
        "recipe[ce-delta-hub]"
      ]
    end
  end

  config.vm.define "ce-engine-1" do |node|
    node.vm.hostname = "ce-engine-1"
    node.vm.network :private_network, ip: "33.33.33.56"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../ce-engine", "/ce-engine"

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "ce_engine" => {
          "destination" => "/ce-engine",
          "user" => "vagrant",
          "ce_operation_hub" => {
            "host" => "ce-operation-hub",
            "stream" => "4001",
            "result" => "4002"
          },
          "ce-delta-hub" => {
            "host" => "ce-delta-hub",
            "stream" => "5002"
          }
        }
      }
      chef.run_list = [
        "recipe[ce-engine]"
      ]
    end
  end

  config.vm.define "ce-engine-2" do |node|
    node.vm.hostname = "ce-engine-2"
    node.vm.network :private_network, ip: "33.33.33.57"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../ce-engine", "/ce-engine"

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "ce_engine" => {
          "destination" => "/ce-engine",
          "user" => "vagrant",
          "ce_operation_hub" => {
            "host" => "ce-operation-hub",
            "stream" => "4001",
            "result" => "4002"
          },
          "ce-delta-hub" => {
            "host" => "ce-delta-hub",
            "stream" => "5002"
          }
        }
      }
      chef.run_list = [
        "recipe[ce-engine]"
      ]
    end
  end

  config.vm.define "ce-engine-3" do |node|
    node.vm.hostname = "ce-engine-3"
    node.vm.network :private_network, ip: "33.33.33.58"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../ce-engine", "/ce-engine"

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "ce_engine" => {
          "destination" => "/ce-engine",
          "user" => "vagrant",
          "ce_operation_hub" => {
            "host" => "ce-operation-hub",
            "stream" => "4001",
            "result" => "4002"
          },
          "ce-delta-hub" => {
            "host" => "ce-delta-hub",
            "stream" => "5002"
          }
        }
      }
      chef.run_list = [
        "recipe[ce-engine]"
      ]
    end
  end
  
  config.vm.define "ce-front-end-1" do |node|
    node.vm.hostname = "ce-front-end-1"
    node.vm.network :private_network, ip: "33.33.33.51"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../ce-front-end", "/ce-front-end"

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "ce_front_end" => {
          "destination" => "/ce-front-end",
          "user" => "vagrant",
          "port" => "3000",
          "ce_operation_hub" => {
            "host" => "ce-operation-hub",
            "submit" => "4000"
          },
          "ce_delta_hub" => {
            "host" => "ce-delta-hub",
            "stream" => "5000",
            "state" => "5001"
          }
        }
      }
      chef.run_list = [
        "recipe[ce-front-end]"
      ]
    end
  end

  config.vm.define "ce-front-end-2" do |node|
    node.vm.hostname = "ce-front-end-2"
    node.vm.network :private_network, ip: "33.33.33.52"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../ce-front-end", "/ce-front-end"

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "ce_front_end" => {
          "destination" => "/ce-front-end",
          "user" => "vagrant",
          "port" => "3000",
          "ce_operation_hub" => {
            "host" => "ce-operation-hub",
            "submit" => "4000"
          },
          "ce_delta_hub" => {
            "host" => "ce-delta-hub",
            "stream" => "5000",
            "state" => "5001"
          }
        }
      }
      chef.run_list = [
        "recipe[ce-front-end]"
      ]
    end
  end

  config.vm.define "ce-front-end-3" do |node|
    node.vm.hostname = "ce-front-end-3"
    node.vm.network :private_network, ip: "33.33.33.53"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../ce-front-end", "/ce-front-end"

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "ce_front_end" => {
          "destination" => "/ce-front-end",
          "user" => "vagrant",
          "port" => "3000",
          "ce_operation_hub" => {
            "host" => "ce-operation-hub",
            "submit" => "4000"
          },
          "ce_delta_hub" => {
            "host" => "ce-delta-hub",
            "stream" => "5000",
            "state" => "5001"
          }
        }
      }
      chef.run_list = [
        "recipe[ce-front-end]"
      ]
    end
  end

  config.vm.define "haproxy" do |node|
    node.vm.hostname = "haproxy"
    node.vm.network :private_network, ip: "33.33.33.50"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.provision :chef_solo do |chef|
      chef.json = {
        "haproxy" => {
          "members" => [{
              "hostname" => "ce-front-end-1",
              "ipaddress" => "33.33.33.51"
            }, {
              "hostname" => "ce-front-end-2",
              "ipaddress" => "33.33.33.52"
            }, {
              "hostname" => "ce-front-end-3",
              "ipaddress" => "33.33.33.53"
            }
          ],
          "member_port" => "3000",
          "admin" => {
            "address_bind" => "0.0.0.0",
            "port" => "8000"
          }
        }
      }
      chef.run_list = [
        "recipe[haproxy]"
      ]
    end
  end

  config.vm.define "test-runner" do |node|
    node.vm.hostname = "test-runner"
    node.vm.network :private_network, ip: "33.33.33.100"
    node.vm.box = "ubuntu1204"
    node.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"

    # ensure /etc/hosts is updated before provisioning with chef
    node.vm.provision :hostmanager

    node.vm.synced_folder "../../test", "/test"

    node.vm.provision :chef_solo do |chef|
      chef.run_list = [
        "recipe[test-runner]"
      ]
    end
  end
end
